name: flutter_ai_chat
description: "Flutter AI Chat Sample"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  all_lint_rules_community: ^0.0.42
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_vertexai: ^1.0.1
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.6.5
  flutter_markdown: ^0.7.3+2
  future_builder_ex: ^4.0.0
  gap: ^3.0.1
  go_router: ^14.2.9
  shared_preferences: ^2.3.2
  split_view: ^3.2.1
  uuid: ^4.5.1

flutter:
  uses-material-design: true
